SRC_URI += "file://user_2018-06-26-17-14-00.cfg"

SRC_URI += "file://0001-brcmfmac-add-CLM-download-support.patch"
SRC_URI += "file://0002-brcmfmac-Set-F2-blksz-and-Watermark-to-256-for-4373.patch"
SRC_URI += "file://0003-brcmfmac-Add-sg-parameters-dts-parsing.patch"
SRC_URI += "file://0004-brcmfmac-return-EPERM-when-getting-error-in-vendor-c.patch"
SRC_URI += "file://0005-brcmfmac-Add-support-for-CYW43012-SDIO-chipset.patch"
SRC_URI += "file://0006-brcmfmac-set-apsta-to-1-when-AP-start-on-primary-int.patch"
SRC_URI += "file://0007-brcmfmac-Saverestore-support-changes-for-43012.patch"
SRC_URI += "file://0008-brcmfmac-Support-43455-save-restore-SR-feature-if-FW.patch"
SRC_URI += "file://0009-brcmfmac-fix-CLM-load-error-for-legacy-chips-when-us.patch"
SRC_URI += "file://0010-brcmfmac-enlarge-buffer-size-of-caps-to-512-bytes.patch"
SRC_URI += "file://0011-brcmfmac-calling-skb_orphan-before-sending-skb-to-SD.patch"
SRC_URI += "file://0012-brcmfmac-43012-Update-F2-Watermark-to-0x60-to-fix-DM.patch"
SRC_URI += "file://0013-brcmfmac-DS1-Exit-should-re-download-the-firmware.patch"
SRC_URI += "file://0014-brcmfmac-add-FT-based-AKMs-in-brcmf_set_key_mgmt-for.patch"
SRC_URI += "file://0015-brcmfmac-Add-support-for-43428-SDIO-device-ID.patch"
SRC_URI += "file://0016-brcmfmac-support-AP-isolation.patch"
SRC_URI += "file://0017-brcmfmac-do-not-print-ulp_sdioctrl-get-error.patch"
SRC_URI += "file://0018-brcmfmac-fix-system-warning-message-during-wowl-susp.patch"
SRC_URI += "file://0019-brcmfmac-add-a-module-parameter-to-set-scheduling-pr.patch"
SRC_URI += "file://0020-brcmfmac-make-firmware-eap_restrict-a-module-paramet.patch"
SRC_URI += "file://0021-brcmfmac-Support-wake-on-ping-packet.patch"
SRC_URI += "file://0022-brcmfmac-Remove-WOWL-configuration-in-disconnect-sta.patch"


FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
